language: node_js
node_js:
  - "7"
  
before_script: 
  - "npm install"
deploy: 
  github_token: $GITHUB_TOKEN
  keep_history: true
  local_dir: build/
  provider: pages
  skip_cleanup: true
  true: 
    branch: master
language: node_js
node_js: 
  - "7"
script: 
  - "echo \"Antes de la construcción\""
  - "npm run build"
